#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
LIB_FILE="$SCRIPT_DIR/lib/ensure-binary-lib.sh"

TOOLS=(claude-irc whip webform redit vaultkey rewind)

check_mode=false
if [ "${1:-}" = "--check" ]; then
    check_mode=true
fi

if [ ! -f "$LIB_FILE" ]; then
    echo "Error: $LIB_FILE not found" >&2
    exit 1
fi

has_diff=false

for tool in "${TOOLS[@]}"; do
    conf_file="$ROOT_DIR/$tool/scripts/ensure-binary.conf"
    output_file="$ROOT_DIR/$tool/scripts/ensure-binary.sh"

    if [ ! -f "$conf_file" ]; then
        echo "Error: $conf_file not found" >&2
        exit 1
    fi

    tmp_file=$(mktemp)

    {
        echo '#!/bin/bash'
        echo "# AUTO-GENERATED by scripts/generate-ensure-binary.sh — DO NOT EDIT"
        echo "# Source: $tool/scripts/ensure-binary.conf + scripts/lib/ensure-binary-lib.sh"
        echo 'set -euo pipefail'
        echo ''
        echo '# === Configuration & Hooks ==='
        cat "$conf_file"
        echo ''
        echo '# === Common Logic ==='
        cat "$LIB_FILE"
    } > "$tmp_file"

    if ! bash -n "$tmp_file"; then
        echo "Error: Generated $tool/scripts/ensure-binary.sh has syntax errors" >&2
        rm -f "$tmp_file"
        exit 1
    fi

    if $check_mode; then
        if [ ! -f "$output_file" ] || ! diff -q "$tmp_file" "$output_file" > /dev/null 2>&1; then
            echo "DIFF: $output_file is out of date" >&2
            has_diff=true
        fi
        rm -f "$tmp_file"
    else
        mv "$tmp_file" "$output_file"
        chmod +x "$output_file"
        echo "Generated: $output_file" >&2
    fi
done

if $check_mode; then
    if $has_diff; then
        echo "Some ensure-binary.sh files are out of date. Run scripts/generate-ensure-binary.sh to regenerate." >&2
        exit 1
    fi
    echo "All ensure-binary.sh files are up to date." >&2
fi
