#!/bin/bash
# AUTO-GENERATED by scripts/generate-ensure-binary.sh — DO NOT EDIT
# Source: vaultkey/scripts/ensure-binary.conf + scripts/lib/ensure-binary-lib.sh
set -e

# === Configuration & Hooks ===
BINARY_NAME="vaultkey"
INSTALL_MODE="global"
VERSION_CHECK="cli"
ENABLE_WINDOWS="true"
SUPPORTED_PLATFORMS=""
BUILD_TARGET="./cmd/vaultkey"

# === Common Logic ===
# Default no-op hooks (overridden by conf if defined before this point)
declare -f pre_upgrade_hook > /dev/null 2>&1 || pre_upgrade_hook() { :; }
declare -f post_install_hook > /dev/null 2>&1 || post_install_hook() { :; }

# --- Setup ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(dirname "$SCRIPT_DIR")"

REPO="bang9/ai-tools"

if [ "$INSTALL_MODE" = "local" ]; then
    INSTALL_DIR="$PLUGIN_ROOT/bin"
else
    INSTALL_DIR="$HOME/.local/bin"
fi
INSTALLED_BINARY="$INSTALL_DIR/$BINARY_NAME"

# --- Expected Version ---
EXPECTED_VERSION=$(grep '"version"' "$PLUGIN_ROOT/.claude-plugin/plugin.json" | head -1 | cut -d'"' -f4)

# --- Version Check ---
if [ "$VERSION_CHECK" = "file" ]; then
    VERSION_FILE="$INSTALL_DIR/.$BINARY_NAME-version"
    if [ -x "$INSTALLED_BINARY" ]; then
        INSTALLED_VERSION=""
        if [ -f "$VERSION_FILE" ]; then
            INSTALLED_VERSION=$(cat "$VERSION_FILE")
        fi
        if [ "$INSTALLED_VERSION" = "$EXPECTED_VERSION" ]; then
            exit 0
        fi
        echo "Upgrading $BINARY_NAME from ${INSTALLED_VERSION:-unknown} to $EXPECTED_VERSION..." >&2
    fi
else
    BINARY_PATH=""
    if command -v "$BINARY_NAME" &> /dev/null; then
        BINARY_PATH="$(command -v "$BINARY_NAME")"
    elif [ -x "$INSTALLED_BINARY" ]; then
        BINARY_PATH="$INSTALLED_BINARY"
    fi
    if [ -n "$BINARY_PATH" ]; then
        INSTALLED_VERSION=$("$BINARY_PATH" --version 2>/dev/null | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' || echo "")
        if [ "$INSTALLED_VERSION" = "$EXPECTED_VERSION" ]; then
            exit 0
        fi
        echo "Upgrading $BINARY_NAME from ${INSTALLED_VERSION:-unknown} to $EXPECTED_VERSION..." >&2
    fi
fi

mkdir -p "$INSTALL_DIR"

# --- Platform Detection ---
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

case "$ARCH" in
    x86_64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

if [ "$ENABLE_WINDOWS" = "true" ]; then
    case "$OS" in
        darwin|linux) ;;
        mingw*|msys*|cygwin*) OS="windows" ;;
        *) echo "Unsupported OS: $OS" >&2; exit 1 ;;
    esac
else
    case "$OS" in
        darwin|linux) ;;
        *) echo "Unsupported OS: $OS" >&2; exit 1 ;;
    esac
fi

if [ -n "${SUPPORTED_PLATFORMS:-}" ]; then
    platform_supported=false
    for supported in $SUPPORTED_PLATFORMS; do
        if [ "$supported" = "${OS}-${ARCH}" ]; then
            platform_supported=true
            break
        fi
    done
    if [ "$platform_supported" != "true" ]; then
        echo "Unsupported platform: ${OS}/${ARCH}. Supported: ${SUPPORTED_PLATFORMS}" >&2
        exit 1
    fi
fi

# --- Download Setup ---
VERSION="$EXPECTED_VERSION"
DOWNLOAD_NAME="${BINARY_NAME}-${OS}-${ARCH}"
CHECKSUMS_NAME="${BINARY_NAME}-checksums.txt"
if [ "$OS" = "windows" ]; then
    DOWNLOAD_NAME="${DOWNLOAD_NAME}.exe"
    INSTALLED_BINARY="${INSTALLED_BINARY}.exe"
fi
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${VERSION}/${DOWNLOAD_NAME}"
CHECKSUMS_URL="https://github.com/${REPO}/releases/download/${VERSION}/${CHECKSUMS_NAME}"

# --- Pre-upgrade Hook ---
pre_upgrade_hook

echo "Downloading $BINARY_NAME ${VERSION}..." >&2

# --- download_file ---
download_file() {
    local url="$1" dest="$2"
    if command -v curl &> /dev/null; then
        curl -fsSL -o "$dest" "$url"
        return $?
    fi
    if command -v wget &> /dev/null; then
        wget -q -O "$dest" "$url"
        return $?
    fi
    echo "Error: neither curl nor wget is available for downloads." >&2
    return 1
}

# --- sha256_file ---
sha256_file() {
    local file="$1"
    if command -v sha256sum &> /dev/null; then
        sha256sum "$file" | awk '{print $1}'
        return $?
    fi
    if command -v shasum &> /dev/null; then
        shasum -a 256 "$file" | awk '{print $1}'
        return $?
    fi
    if command -v openssl &> /dev/null; then
        openssl dgst -sha256 "$file" | awk '{print $NF}'
        return $?
    fi
    echo "Error: no SHA-256 tool found (tried sha256sum, shasum, openssl)." >&2
    return 1
}

# --- lookup_checksum ---
lookup_checksum() {
    local manifest="$1" asset_name="$2"
    awk -v name="$asset_name" '
        NF >= 2 {
            file = $2
            sub(/^\*/, "", file)
            if (file == name) {
                print $1
                exit
            }
        }
    ' "$manifest"
}

# --- safe_install ---
safe_install() {
    local url="$1" dest="$2" asset_name="$3" checksum_url="$4"
    local tmp="${dest}.tmp.$$" manifest="${tmp}.checksums"
    local expected_checksum actual_checksum

    if ! download_file "$checksum_url" "$manifest"; then
        echo "Failed to download checksum manifest: $checksum_url" >&2
        rm -f "$tmp" "$manifest"
        return 1
    fi

    expected_checksum=$(lookup_checksum "$manifest" "$asset_name")
    if [ -z "$expected_checksum" ]; then
        echo "Checksum entry not found for $asset_name in $checksum_url" >&2
        rm -f "$tmp" "$manifest"
        return 1
    fi

    if ! download_file "$url" "$tmp"; then
        rm -f "$tmp" "$manifest"
        return 1
    fi

    if ! actual_checksum=$(sha256_file "$tmp"); then
        rm -f "$tmp" "$manifest"
        return 1
    fi

    if [ "$actual_checksum" != "$expected_checksum" ]; then
        echo "Checksum mismatch for $asset_name: expected $expected_checksum, got $actual_checksum" >&2
        rm -f "$tmp" "$manifest"
        return 1
    fi

    if ! chmod +x "$tmp"; then
        rm -f "$tmp" "$manifest"
        return 1
    fi

    rm -f "$dest"
    if ! mv "$tmp" "$dest"; then
        rm -f "$tmp" "$manifest"
        return 1
    fi

    rm -f "$manifest"
    return 0
}

# --- record_version (file-based version tracking) ---
record_version() {
    if [ "$VERSION_CHECK" = "file" ]; then
        echo "$VERSION" > "$VERSION_FILE"
    fi
}

# --- Download & Install ---
if safe_install "$DOWNLOAD_URL" "$INSTALLED_BINARY" "$DOWNLOAD_NAME" "$CHECKSUMS_URL"; then
    record_version
    echo "$BINARY_NAME ${VERSION} installed to $INSTALLED_BINARY" >&2
    post_install_hook
    exit 0
fi

echo "Failed to download binary. Trying to build from source..." >&2

# --- Build from Source ---
if command -v go &> /dev/null; then
    echo "Building $BINARY_NAME from source..." >&2
    cd "$PLUGIN_ROOT"
    go build -o "$INSTALLED_BINARY" "$BUILD_TARGET"
    record_version
    echo "$BINARY_NAME built successfully" >&2
    exit 0
fi

echo "Error: Could not download binary and Go is not installed." >&2
echo "Please install Go or download manually from:" >&2
echo "  ${DOWNLOAD_URL}" >&2
exit 1
